In [18]:
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt

data = pd.read_csv('/kaggle/input/digit-recognizer/train.csv')

In [19]:
data.head()

label  pixel0  pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  \
0      1       0       0       0       0       0       0       0       0   
1      0       0       0       0       0       0       0       0       0   
2      1       0       0       0       0       0       0       0       0   
3      4       0       0       0       0       0       0       0       0   
4      0       0       0       0       0       0       0       0       0   

   pixel8  ...  pixel774  pixel775  pixel776  pixel777  pixel778  pixel779  \
0       0  ...         0         0         0         0         0         0   
1       0  ...         0         0         0         0         0         0   
2       0  ...         0         0         0         0         0         0   
3       0  ...         0         0         0         0         0         0   
4       0  ...         0         0         0         0         0         0   

   pixel780  pixel781  pixel782  pixel783  
0         0         0         0         0  
1         0         0         0         0  
2         0         0         0         0  
3         0         0         0         0  
4         0         0         0         0  

[5 rows x 785 columns]

In [20]:
data = np.array(data)
m, n = data.shape
np.random.shuffle(data) # shuffle before splitting into dev and training sets

data_dev = data[0:1000].T
Y_dev = data_dev[0]
X_dev = data_dev[1:n]
X_dev = X_dev / 255.

data_train = data[1000:m].T
Y_train = data_train[0]
X_train = data_train[1:n]
X_train = X_train / 255.
_,m_train = X_train.shape

In [21]:
Y_train

array([2, 6, 6, ..., 8, 8, 8])

In [22]:
def init_params():
    W1 = np.random.rand(10, 784) - 0.5
    b1 = np.random.rand(10, 1) - 0.5
    W2 = np.random.rand(10, 10) - 0.5
    b2 = np.random.rand(10, 1) - 0.5
    return W1, b1, W2, b2

def ReLU(Z):
    return np.maximum(Z, 0)

def softmax(Z):
    A = np.exp(Z) / sum(np.exp(Z))
    return A
    
def forward_prop(W1, b1, W2, b2, X):
    Z1 = W1.dot(X) + b1
    A1 = ReLU(Z1)
    Z2 = W2.dot(A1) + b2
    A2 = softmax(Z2)
    return Z1, A1, Z2, A2

def ReLU_deriv(Z):
    return Z > 0

def one_hot(Y):
    one_hot_Y = np.zeros((Y.size, Y.max() + 1))
    one_hot_Y[np.arange(Y.size), Y] = 1
    one_hot_Y = one_hot_Y.T
    return one_hot_Y

def backward_prop(Z1, A1, Z2, A2, W1, W2, X, Y):
    one_hot_Y = one_hot(Y)
    dZ2 = A2 - one_hot_Y
    dW2 = 1 / m * dZ2.dot(A1.T)
    db2 = 1 / m * np.sum(dZ2)
    dZ1 = W2.T.dot(dZ2) * ReLU_deriv(Z1)
    dW1 = 1 / m * dZ1.dot(X.T)
    db1 = 1 / m * np.sum(dZ1)
    return dW1, db1, dW2, db2

def update_params(W1, b1, W2, b2, dW1, db1, dW2, db2, alpha):
    W1 = W1 - alpha * dW1
    b1 = b1 - alpha * db1    
    W2 = W2 - alpha * dW2  
    b2 = b2 - alpha * db2    
    return W1, b1, W2, b2

In [23]:
def get_predictions(A2):
    return np.argmax(A2, 0)

def get_accuracy(predictions, Y):
    print(predictions, Y)
    return np.sum(predictions == Y) / Y.size

def gradient_descent(X, Y, alpha, iterations):
    W1, b1, W2, b2 = init_params()
    for i in range(iterations):
        Z1, A1, Z2, A2 = forward_prop(W1, b1, W2, b2, X)
        dW1, db1, dW2, db2 = backward_prop(Z1, A1, Z2, A2, W1, W2, X, Y)
        W1, b1, W2, b2 = update_params(W1, b1, W2, b2, dW1, db1, dW2, db2, alpha)
        if i % 10 == 0:
            print("Iteration: ", i)
            predictions = get_predictions(A2)
            print(get_accuracy(predictions, Y))
    return W1, b1, W2, b2

In [26]:
W1, b1, W2, b2 = gradient_descent(X_train, Y_train, 0.20, 500)

Iteration:  0
[7 9 9 ... 7 9 2] [2 6 6 ... 8 8 8]
0.11502439024390244
Iteration:  10
[3 9 9 ... 2 3 1] [2 6 6 ... 8 8 8]
0.37558536585365854
Iteration:  20
[3 8 6 ... 8 8 1] [2 6 6 ... 8 8 8]
0.48434146341463413
Iteration:  30
[8 6 6 ... 8 8 1] [2 6 6 ... 8 8 8]
0.5577560975609757
Iteration:  40
[8 6 6 ... 8 8 1] [2 6 6 ... 8 8 8]
0.6188536585365854
Iteration:  50
[8 6 6 ... 8 8 8] [2 6 6 ... 8 8 8]
0.6636585365853659
Iteration:  60
[8 6 6 ... 8 8 8] [2 6 6 ... 8 8 8]
0.7001463414634146
Iteration:  70
[8 6 6 ... 8 8 8] [2 6 6 ... 8 8 8]
0.727390243902439
Iteration:  80
[3 6 6 ... 8 8 8] [2 6 6 ... 8 8 8]
0.7492682926829268
Iteration:  90
[3 6 6 ... 8 8 8] [2 6 6 ... 8 8 8]
0.7661463414634146
Iteration:  100
[2 6 6 ... 8 8 8] [2 6 6 ... 8 8 8]
0.7793170731707317
Iteration:  110
[2 6 6 ... 8 8 8] [2 6 6 ... 8 8 8]
0.789829268292683
Iteration:  120
[2 6 6 ... 8 8 8] [2 6 6 ... 8 8 8]
0.7977317073170732
Iteration:  130
[2 6 6 ... 8 8 8] [2 6 6 ... 8 8 8]
0.7994634146341464
Iteration:  140
